## Server
server:
  port: ${SERVER_PORT:9001}

## MySQL
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/twitter?serverTimezone=UTC&useLegacyDatetimeCode=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:passw}

ums:
  host: ${UMS_HOST:http://localhost}
  port: ${UMS_PORT:9000}
  paths:
    user: /users/user

# JWT
jwt:
  secret: ${JWT_SECRET:default-secret-if-not-set-1234567}
  expiration: ${JWT_EXPIRATION:3600000}
