apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - host: minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-ui-service
                port:
                  number: 80
          - path: /ums
            pathType: Prefix
            backend:
              service:
                name: ums-service
                port:
                  number: 9000
          - path: /twitter
            pathType: Prefix
            backend:
              service:
                name: twitter-service
                port:
                  number: 9001