apiVersion: v1
kind: ConfigMap
metadata:
  name: twitter-config
data:
  SERVER_PORT: "9001"

  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/twitter?serverTimezone=UTC"
  SPRING_DATASOURCE_USERNAME: "root"

  UMS_HOST: "http://ums-service:9000"

  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
