apiVersion: v1
kind: ConfigMap
metadata:
  name: ums-config
data:
  SERVER_PORT: "9000"

  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/ums?serverTimezone=UTC&useSSL=false"
  SPRING_DATASOURCE_USERNAME: "root"

  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQL8Dialect"

  SPRING_PROFILES_ACTIVE: "k8s"
