## Server
server:
  port: ${SERVER_PORT:9000}

## MySQL
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://0.0.0.0:3306/ums?serverTimezone=UTC&useLegacyDatetimeCode=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:passw}

# JWT
jwt:
  secret: ${JWT_SECRET:default-secret-if-not-set-1234567}
  expiration: ${JWT_EXPIRATION:3600000}
